name: Scrape Timetable

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install pipenv
      run: python -m pip install pipenv
    - name: Install dependencies
      run: |
        cd anuscrape
        python -m pipenv install
    - name: Run scraper
      run: |
        cd anuscrape
        pipenv run ./scrape_prepare.sh
    - name: Diff
      run: git diff
